# Generated by Django 4.2.27 on 2026-01-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
